export const SEVERITY_CONFIG = {
  Critical: { color: 'bg-red-500/20 text-red-400 border-red-500/30', dot: 'bg-red-500', badge: 'bg-red-500 text-white' },
  High: { color: 'bg-orange-500/20 text-orange-400 border-orange-500/30', dot: 'bg-orange-500', badge: 'bg-orange-500 text-white' },
  Medium: { color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30', dot: 'bg-yellow-500', badge: 'bg-yellow-500 text-black' },
  Low: { color: 'bg-green-500/20 text-green-400 border-green-500/30', dot: 'bg-green-500', badge: 'bg-green-500 text-white' },
};

export const STATUS_CONFIG = {
  Open: { color: 'bg-red-500/20 text-red-400', label: 'פתוח' },
  'Under Investigation': { color: 'bg-yellow-500/20 text-yellow-400', label: 'בחקירה' },
  Contained: { color: 'bg-blue-500/20 text-blue-400', label: 'הוכל' },
  Closed: { color: 'bg-green-500/20 text-green-400', label: 'סגור' },
};

export const EVENT_TYPES = ['Phishing', 'Malware', 'Privilege Escalation', 'Custom'];
export const DETECTION_SOURCES = ['EDR', 'Firewall', 'Active Directory', 'SAP', 'Salesforce', 'Intune', 'Mail Gateway'];
export const STATUSES = ['Open', 'Under Investigation', 'Contained', 'Closed'];
export const SEVERITIES = ['Low', 'Medium', 'High', 'Critical'];

export const demoEvents = [
  {
    id: 'EVT-001',
    title: 'חשד להעלאת הרשאות חריגה ב-Active Directory',
    description: 'זוהה שינוי הרשאות חריג בחשבון Domain Admin ללא כרטיס שינוי מאושר. המשתמש admin.ops ביצע הוספת הרשאות לקבוצת Enterprise Admins.',
    eventType: 'Privilege Escalation',
    severity: 'Critical',
    status: 'Open',
    detectionSource: 'Active Directory',
    reportedTime: '2026-06-03T08:15:00',
    assignedAnalyst: 'דני כהן',
    virusTotalResult: null,
    mitreMapping: ['T1078 - Valid Accounts', 'T1098 - Account Manipulation'],
    timeline: [
      { time: '08:15', action: 'זוהה שינוי הרשאות חריג', actor: 'SIEM' },
      { time: '08:18', action: 'אלרט נשלח לצוות SOC', actor: 'מערכת' },
      { time: '08:22', action: 'אנליסט Tier 1 החל בחקירה', actor: 'דני כהן' },
      { time: '08:35', action: 'נבדק מול ITSM - לא נמצא כרטיס שינוי', actor: 'דני כהן' },
    ],
    evidence: {
      files: [],
      hashes: [],
      ips: ['10.0.50.12', '10.0.50.1'],
      urls: [],
      logs: ['Event ID 4728: Member added to security-enabled global group', 'Event ID 4732: Member added to Enterprise Admins'],
    },
  },
  {
    id: 'EVT-002',
    title: 'מייל Phishing שנשלח למספר עובדים',
    description: 'זוהו 15 מיילים חשודים מכתובת support@micr0soft-update.com המכילים קישור זדוני לדף כניסה מזויף של Office 365.',
    eventType: 'Phishing',
    severity: 'High',
    status: 'Under Investigation',
    detectionSource: 'Mail Gateway',
    reportedTime: '2026-06-03T07:30:00',
    assignedAnalyst: 'מיכל לוי',
    virusTotalResult: { score: '12/72', threat: 'Phishing', recommendation: 'חסימה' },
    mitreMapping: ['T1566.001 - Spearphishing Attachment', 'T1598 - Phishing for Information'],
    timeline: [
      { time: '07:30', action: 'דיווח ממשתמש על מייל חשוד', actor: 'עובד' },
      { time: '07:35', action: 'Mail Gateway זיהה 15 מיילים דומים', actor: 'Mail Gateway' },
      { time: '07:40', action: 'אנליסט Tier 1 החל בחקירה', actor: 'מיכל לוי' },
      { time: '07:55', action: 'בדיקת URL ב-VirusTotal - זדוני', actor: 'מיכל לוי' },
      { time: '08:05', action: 'חסימת דומיין בפיירוול', actor: 'מערכת אוטומטית' },
    ],
    evidence: {
      files: ['invoice_update.html'],
      hashes: ['a1b2c3d4e5f6789012345678abcdef01'],
      ips: ['185.234.72.19'],
      urls: ['https://micr0soft-update.com/login', 'https://micr0soft-update.com/verify'],
      logs: ['15 emails blocked by Mail Gateway', 'URL categorized as Phishing'],
    },
  },
  {
    id: 'EVT-003',
    title: 'זיהוי קובץ Ransomware בתחנת קצה',
    description: 'מערכת EDR זיהתה קובץ חשוד בשם svchost_update.exe בתחנת עבודה של מחלקת הנדסה. הקובץ מנסה להצפין קבצים מקומיים.',
    eventType: 'Malware',
    severity: 'High',
    status: 'Contained',
    detectionSource: 'EDR',
    reportedTime: '2026-06-02T22:45:00',
    assignedAnalyst: 'יוסי אברהם',
    virusTotalResult: { score: '58/72', threat: 'Ransomware.Win32.LockBit', recommendation: 'הסגר ובידוד' },
    mitreMapping: ['T1486 - Data Encrypted for Impact', 'T1059 - Command and Scripting Interpreter'],
    timeline: [
      { time: '22:45', action: 'EDR זיהה קובץ זדוני', actor: 'CrowdStrike EDR' },
      { time: '22:46', action: 'בידוד אוטומטי של התחנה', actor: 'EDR' },
      { time: '22:50', action: 'אלרט נשלח לצוות SOC', actor: 'מערכת' },
      { time: '22:55', action: 'אנליסט Tier 2 החל בחקירה', actor: 'יוסי אברהם' },
      { time: '23:10', action: 'Hash נבדק ב-VirusTotal - מזוהה כ-LockBit', actor: 'יוסי אברהם' },
      { time: '23:30', action: 'סריקה רוחבית הושלמה - לא נמצאו תחנות נוספות', actor: 'EDR' },
    ],
    evidence: {
      files: ['svchost_update.exe', 'readme_restore.txt'],
      hashes: ['e99a18c428cb38d5f260853678922e03', 'd41d8cd98f00b204e9800998ecf8427e'],
      ips: ['192.168.1.105', '45.33.32.156'],
      urls: ['http://lockbit-decrypt.onion'],
      logs: ['Process svchost_update.exe spawned by explorer.exe', 'File encryption attempt blocked'],
    },
  },
  {
    id: 'EVT-004',
    title: 'ניסיון גישה חשוד ל-Salesforce ממדינה לא מוכרת',
    description: 'זוהה ניסיון כניסה לחשבון Salesforce של מנהל מכירות מכתובת IP ברוסיה, בשעה חריגה.',
    eventType: 'Custom',
    severity: 'Medium',
    status: 'Open',
    detectionSource: 'Salesforce',
    reportedTime: '2026-06-03T03:20:00',
    assignedAnalyst: 'רונית שמש',
    virusTotalResult: null,
    mitreMapping: ['T1078 - Valid Accounts', 'T1110 - Brute Force'],
    timeline: [
      { time: '03:20', action: 'ניסיון כניסה חשוד ל-Salesforce', actor: 'Salesforce CASB' },
      { time: '03:22', action: 'MFA נדרש - לא הושלם', actor: 'Salesforce' },
      { time: '06:00', action: 'אלרט נבדק על ידי אנליסט', actor: 'רונית שמש' },
    ],
    evidence: {
      files: [],
      hashes: [],
      ips: ['91.234.56.78'],
      urls: [],
      logs: ['Failed login attempt from IP 91.234.56.78 (RU)', 'MFA challenge not completed'],
    },
  },
  {
    id: 'EVT-005',
    title: 'מכשיר נייד שאינו עומד במדיניות Intune',
    description: 'מכשיר iPhone של עובד מחלקת כספים אינו מעודכן ולא עומד בדרישות מדיניות Compliance של Intune.',
    eventType: 'Custom',
    severity: 'Medium',
    status: 'Closed',
    detectionSource: 'Intune',
    reportedTime: '2026-06-01T14:00:00',
    assignedAnalyst: 'אילן מזרחי',
    virusTotalResult: null,
    mitreMapping: ['T1078.004 - Cloud Accounts'],
    timeline: [
      { time: '14:00', action: 'Intune דיווח על Non-Compliance', actor: 'Microsoft Intune' },
      { time: '14:30', action: 'נשלחה התראה לעובד', actor: 'מערכת' },
      { time: '16:00', action: 'העובד עדכן את המכשיר', actor: 'עובד' },
      { time: '16:15', action: 'המכשיר חזר למצב Compliant', actor: 'Intune' },
      { time: '16:20', action: 'האירוע נסגר', actor: 'אילן מזרחי' },
    ],
    evidence: {
      files: [],
      hashes: [],
      ips: [],
      urls: [],
      logs: ['Device non-compliant: OS version outdated', 'Compliance restored after update'],
    },
  },
];

export const trendData = [
  { day: '28/05', Critical: 1, High: 3, Medium: 5, Low: 2 },
  { day: '29/05', Critical: 2, High: 4, Medium: 3, Low: 4 },
  { day: '30/05', Critical: 0, High: 2, Medium: 6, Low: 3 },
  { day: '31/05', Critical: 3, High: 5, Medium: 4, Low: 1 },
  { day: '01/06', Critical: 1, High: 3, Medium: 5, Low: 5 },
  { day: '02/06', Critical: 2, High: 4, Medium: 3, Low: 2 },
  { day: '03/06', Critical: 1, High: 2, Medium: 4, Low: 3 },
];

export const playbooks = [
  {
    id: 'PB-001',
    name: 'Phishing Email Response',
    description: 'תגובה לאירועי Phishing שמזוהים דרך דיווח משתמשים או Mail Gateway',
    trigger: 'דיווח משתמש או זיהוי Mail Gateway',
    severity: 'High',
    detectionSource: 'Mail Gateway',
    status: 'Active',
    executions: 12,
    lastRun: '2026-06-03T07:40:00',
    steps: [
      { order: 1, title: 'קבלת אלרט', description: 'זיהוי מייל חשוד דרך דיווח משתמש או Mail Gateway', type: 'trigger', auto: true },
      { order: 2, title: 'בדיקת כתובת שולח', description: 'אימות כתובת השולח מול רשימת דומיינים מוכרים', type: 'investigation', auto: true },
      { order: 3, title: 'ניתוח קישורים וקבצים', description: 'חילוץ URLs וקבצים מצורפים מהמייל', type: 'investigation', auto: true },
      { order: 4, title: 'בדיקה מול VirusTotal', description: 'שליחת URLs, Hashes ודומיינים לבדיקה ב-VirusTotal', type: 'investigation', auto: true },
      { order: 5, title: 'מחיקת מיילים נוספים', description: 'חיפוש ומחיקת מיילים דומים מתיבות דואר נוספות', type: 'containment', auto: true },
      { order: 6, title: 'חסימת דומיין/URL', description: 'הוספת דומיין או URL זדוני לרשימת חסימה בפיירוול', type: 'containment', auto: true },
      { order: 7, title: 'איפוס סיסמה', description: 'איפוס סיסמה למשתמש שהזין פרטים בדף המזויף', type: 'response', auto: false },
      { order: 8, title: 'סגירה או הסלמה', description: 'סגירת האירוע או הסלמה ל-Tier 2 לפי ממצאים', type: 'closure', auto: false },
    ],
    escalation: 'הסלמה ל-Tier 2 אם יותר מ-5 משתמשים לחצו על הקישור',
    closureCondition: 'כל המיילים נמחקו, הדומיין נחסם, ולא זוהתה דליפת מידע',
  },
  {
    id: 'PB-002',
    name: 'Privilege Escalation Response',
    description: 'תגובה לאירועי העלאת הרשאות חריגה ב-Active Directory',
    trigger: 'שינוי הרשאות חריג ב-Active Directory',
    severity: 'Critical',
    detectionSource: 'Active Directory',
    status: 'Active',
    executions: 5,
    lastRun: '2026-06-03T08:18:00',
    steps: [
      { order: 1, title: 'זיהוי שינוי הרשאות', description: 'SIEM מזהה Event ID 4728/4732 חריג', type: 'trigger', auto: true },
      { order: 2, title: 'בדיקת כרטיס שינוי ב-ITSM', description: 'בדיקה האם קיים כרטיס Change Request מאושר', type: 'investigation', auto: true },
      { order: 3, title: 'בדיקת המשתמש המבצע', description: 'זיהוי מי ביצע את שינוי ההרשאות', type: 'investigation', auto: true },
      { order: 4, title: 'בדיקת המשתמש המקבל', description: 'בדיקה למי ניתנו הרשאות חדשות', type: 'investigation', auto: true },
      { order: 5, title: 'העלאת חומרה ל-Critical', description: 'אם אין אישור ITSM - העלאת חומרה מיידית', type: 'response', auto: true },
      { order: 6, title: 'נעילת חשבון חשוד', description: 'נעילת החשבון שביצע את הפעולה', type: 'containment', auto: true },
      { order: 7, title: 'ניתוק Sessions פעילים', description: 'ניתוק כל ה-Sessions הפעילים של החשבון', type: 'containment', auto: true },
      { order: 8, title: 'ביטול הרשאות חריגות', description: 'הסרת ההרשאות שנוספו שלא כדין', type: 'containment', auto: true },
      { order: 9, title: 'הסלמה ל-Tier 2 ומנהל SOC', description: 'דיווח מלא להנהלת SOC', type: 'closure', auto: false },
    ],
    escalation: 'הסלמה מיידית ל-Tier 2 ולמנהל SOC אם אין כרטיס שינוי מאושר',
    closureCondition: 'ההרשאות בוטלו, החשבון נבדק, ואושר כי אין פגיעה נוספת',
  },
  {
    id: 'PB-003',
    name: 'EDR Alert - Virus Detection',
    description: 'תגובה לזיהוי קובץ זדוני בתחנת קצה דרך מערכת EDR',
    trigger: 'זיהוי קובץ זדוני בתחנת קצה',
    severity: 'High',
    detectionSource: 'EDR',
    status: 'Active',
    executions: 8,
    lastRun: '2026-06-02T22:46:00',
    steps: [
      { order: 1, title: 'קבלת אלרט מ-EDR', description: 'זיהוי קובץ זדוני בתחנת קצה', type: 'trigger', auto: true },
      { order: 2, title: 'שליפת פרטי תחנה', description: 'Host ID, כתובת IP, שם משתמש, שם קובץ ו-Hash', type: 'investigation', auto: true },
      { order: 3, title: 'בדיקת Hash ב-VirusTotal', description: 'שליחת ה-Hash לבדיקה ב-VirusTotal', type: 'investigation', auto: true },
      { order: 4, title: 'בידוד לוגי של התחנה', description: 'בידוד התחנה מהרשת באמצעות EDR', type: 'containment', auto: true },
      { order: 5, title: 'העברת קובץ להסגר', description: 'הזזת הקובץ הזדוני לתיקיית הסגר', type: 'containment', auto: true },
      { order: 6, title: 'סריקה רוחבית', description: 'סריקת תחנות נוספות ברשת עבור אותו Hash', type: 'investigation', auto: true },
      { order: 7, title: 'פתיחת כרטיס ל-Tier 2', description: 'פתיחת כרטיס טיפול לאנליסט Tier 2', type: 'response', auto: true },
      { order: 8, title: 'סגירה לאחר ניקוי ואישור', description: 'סגירת האירוע לאחר אישור שהתחנה נקייה', type: 'closure', auto: false },
    ],
    escalation: 'הסלמה ל-Tier 2 אם נמצאו תחנות נוספות נגועות',
    closureCondition: 'הקובץ הוסר, התחנה נוקתה, ולא זוהו תחנות נוספות נגועות',
  },
];

export const mitreAttackData = {
  techniques: [
    { id: 'T1566.001', name: 'Spearphishing Attachment', tactic: 'Initial Access', description: 'שליחת מייל עם קובץ זדוני מצורף', relevance: 'High' },
    { id: 'T1078', name: 'Valid Accounts', tactic: 'Defense Evasion', description: 'שימוש בחשבונות לגיטימיים לגישה לא מורשית', relevance: 'Critical' },
    { id: 'T1098', name: 'Account Manipulation', tactic: 'Persistence', description: 'שינוי הרשאות חשבונות לשמירת גישה', relevance: 'Critical' },
    { id: 'T1486', name: 'Data Encrypted for Impact', tactic: 'Impact', description: 'הצפנת נתונים לצורך סחיטה', relevance: 'High' },
    { id: 'T1059', name: 'Command and Scripting Interpreter', tactic: 'Execution', description: 'הרצת פקודות זדוניות באמצעות כלי סקריפטינג', relevance: 'Medium' },
    { id: 'T1110', name: 'Brute Force', tactic: 'Credential Access', description: 'ניסיון לפצח סיסמאות בכוח', relevance: 'Medium' },
    { id: 'T1078.004', name: 'Cloud Accounts', tactic: 'Defense Evasion', description: 'שימוש בחשבונות ענן לגישה לא מורשית', relevance: 'Medium' },
    { id: 'T1021', name: 'Remote Services', tactic: 'Lateral Movement', description: 'תנועה רוחבית ברשת באמצעות שירותים מרוחקים', relevance: 'High' },
    { id: 'T1071', name: 'Application Layer Protocol', tactic: 'Command and Control', description: 'שימוש בפרוטוקולי שכבת אפליקציה לתקשורת C2', relevance: 'Medium' },
    { id: 'T1048', name: 'Exfiltration Over Alternative Protocol', tactic: 'Exfiltration', description: 'חילוץ נתונים באמצעות פרוטוקולים חלופיים', relevance: 'High' },
    { id: 'T1562', name: 'Impair Defenses', tactic: 'Defense Evasion', description: 'השבתת מנגנוני הגנה כמו AV ו-EDR', relevance: 'Critical' },
    { id: 'T0855', name: 'Unauthorized Command Message (ICS)', tactic: 'Impair Process Control', description: 'שליחת פקודות לא מורשות למערכות SCADA/ICS', relevance: 'Critical' },
  ],
  threatGroups: [
    { name: 'Sandworm Team / Electrum', origin: 'רוסיה', target: 'תשתיות חשמל, Energy', techniques: ['T1059', '1486', 'T0855'], description: 'קבוצת תקיפה ממומנת מדינה, אחראית על מתקפות נגד רשתות חשמל באוקראינה' },
    { name: 'APT33 / Elfin', origin: 'איראן', target: 'אנרגיה, תעופה', techniques: ['T1566.001', 'T1078', 'T1110'], description: 'קבוצת ריגול שמתמקדת בתשתיות אנרגיה ותעופה' },
    { name: 'Xenotime', origin: 'לא ידוע', target: 'ICS, Safety Systems', techniques: ['T0855', 'T1021', 'T1562'], description: 'קבוצה מתקדמת שתוקפת מערכות בטיחות תעשייתיות (SIS)' },
  ],
};

export const virusTotalDemoResults = [
  { query: 'e99a18c428cb38d5f260853678922e03', type: 'Hash', score: '58/72', engines: 72, detected: 58, threat: 'Ransomware.Win32.LockBit', recommendation: 'הסגר ובידוד מיידי', risk: 'Critical' },
  { query: '185.234.72.19', type: 'IP', score: '12/72', engines: 72, detected: 12, threat: 'Phishing Infrastructure', recommendation: 'חסימה בפיירוול', risk: 'High' },
  { query: 'micr0soft-update.com', type: 'Domain', score: '45/72', engines: 72, detected: 45, threat: 'Phishing Domain', recommendation: 'חסימה מיידית', risk: 'Critical' },
];